name: tab_scaffold
description: A new Flutter package project.
version: 0.1.3+1
homepage: https://github.com/dshukertjr/scaffold_tab

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
